### ISSUE TITLE
Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic

### ISSUE THREAD

**Issue by palmertime** [autostructure/artifactory_pro#1]
I get an error when trying trying to apply this module.  Seems like it is trying to create the license file before artifactory is installed and the directory structure created.

Puppet version: 3.8.6
OS: Oracle Linux 7.2
artifactory reference: v2.0.5
artifactory_pro reference: 4f8f227e284f1205a599f34cc8c96d4ecbcd6ebb

node.pp file:
node 'af-server' {
  class { '::artifactory_pro':
    license_key => 'XXXXXXXXXX',
  }
}

Error:
Error: Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock at 18:/tmp/vagrant-puppet/modules-f2a81f94ed07a1272648775be749b435/artifactory_pro/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock at 18:/tmp/vagrant-puppet/modules-f2a81f94ed07a1272648775be749b435/artifactory_pro/manifests/config.pp
Wrapped exception:
No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock
Error: /Stage[main]/Artifactory_pro::Config/File[/var/opt/jfrog/artifactory/etc/artifactory.lic]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock at 18:/tmp/vagrant-puppet/modules-f2a81f94ed07a1272648775be749b435/artifactory_pro/manifests/config.pp
Error: Cannot create /var/opt/jfrog/artifactory/etc/plugins; parent directory /var/opt/jfrog/artifactory/etc does not exist
Error: /Stage[main]/Artifactory_pro::Config/File[/var/opt/jfrog/artifactory/etc/plugins]/ensure: change from absent to directory failed: Cannot create /var/opt/jfrog/artifactory/etc/plugins; parent directory /var/opt/jfrog/artifactory/etc does not exist

**Comment by bryanjbelanger** [comment]
I think I know what's happening. Will fix it tonight.

On Aug 25, 2016, at 1:59 PM, palmertime <notifications@github.com<mailto:notifications@github.com>> wrote:


I get an error when trying trying to apply this module. Seems like it is trying to create the license file before artifactory is installed and the directory structure created.

Puppet version: 3.8.6
OS: Oracle Linux 7.2
artifactory reference: v2.0.5
artifactory_pro reference: 4f8f227<https://github.com/autostructure/artifactory_pro/commit/4f8f227e284f1205a599f34cc8c96d4ecbcd6ebb>

node.pp file:
node 'af-server' {
class { '::artifactory_pro':
license_key => 'XXXXXXXXXX',
}
}

Error:
Error: Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock at 18:/tmp/vagrant-puppet/modules-f2a81f94ed07a1272648775be749b435/artifactory_pro/manifests/config.pp
Error: Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock at 18:/tmp/vagrant-puppet/modules-f2a81f94ed07a1272648775be749b435/artifactory_pro/manifests/config.pp
Wrapped exception:
No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock
Error: /Stage[main]/Artifactory_pro::Config/File[/var/opt/jfrog/artifactory/etc/artifactory.lic]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory - /var/opt/jfrog/artifactory/etc/artifactory.lic20160825-12794-1pblh.lock at 18:/tmp/vagrant-puppet/modules-f2a81f94ed07a1272648775be749b435/artifactory_pro/manifests/config.pp
Error: Cannot create /var/opt/jfrog/artifactory/etc/plugins; parent directory /var/opt/jfrog/artifactory/etc does not exist
Error: /Stage[main]/Artifactory_pro::Config/File[/var/opt/jfrog/artifactory/etc/plugins]/ensure: change from absent to directory failed: Cannot create /var/opt/jfrog/artifactory/etc/plugins; parent directory /var/opt/jfrog/artifactory/etc does not exist

-

**Comment by bryanjbelanger** [comment]
Please go ahead and try the new version.

I added ordering to ensure Artifactory base is configured first.

**Comment by palmertime** [comment]
Confirmed!  That commit fixed the issue.  Greatly appreciated.
